/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUserCodeRouteImport } from './routes/u.$userCode'
import { Route as CatalogProductIdRouteImport } from './routes/catalog.$productId'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginOtpRouteImport } from './routes/auth/login-otp'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedTradeIndexRouteImport } from './routes/_authenticated/trade/index'
import { Route as AuthenticatedSupportIndexRouteImport } from './routes/_authenticated/support/index'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedTradeIdRouteImport } from './routes/_authenticated/trade/$id'
import { Route as AuthenticatedServicesHsCodesRouteImport } from './routes/_authenticated/services/hs-codes'
import { Route as AuthenticatedServicesCircularsRouteImport } from './routes/_authenticated/services/circulars'
import { Route as AuthenticatedProductsNewRouteImport } from './routes/_authenticated/products/new'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin/support'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin/products'
import { Route as AuthenticatedAdminDocumentsRouteImport } from './routes/_authenticated/admin/documents'
import { Route as AuthenticatedAdminCircularsRouteImport } from './routes/_authenticated/admin/circulars'
import { Route as AuthenticatedAdminAdsRouteImport } from './routes/_authenticated/admin/ads'
import { Route as AuthenticatedAdminUsersUserIdRouteImport } from './routes/_authenticated/admin/users.$userId'

const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUserCodeRoute = UUserCodeRouteImport.update({
  id: '/u/$userCode',
  path: '/u/$userCode',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogProductIdRoute = CatalogProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => CatalogRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginOtpRoute = AuthLoginOtpRouteImport.update({
  id: '/auth/login-otp',
  path: '/auth/login-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTradeIndexRoute = AuthenticatedTradeIndexRouteImport.update({
  id: '/trade/',
  path: '/trade/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSupportIndexRoute =
  AuthenticatedSupportIndexRouteImport.update({
    id: '/support/',
    path: '/support/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTradeIdRoute = AuthenticatedTradeIdRouteImport.update({
  id: '/trade/$id',
  path: '/trade/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedServicesHsCodesRoute =
  AuthenticatedServicesHsCodesRouteImport.update({
    id: '/services/hs-codes',
    path: '/services/hs-codes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServicesCircularsRoute =
  AuthenticatedServicesCircularsRouteImport.update({
    id: '/services/circulars',
    path: '/services/circulars',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsNewRoute =
  AuthenticatedProductsNewRouteImport.update({
    id: '/products/new',
    path: '/products/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/admin/support',
    path: '/admin/support',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/admin/products',
    path: '/admin/products',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDocumentsRoute =
  AuthenticatedAdminDocumentsRouteImport.update({
    id: '/admin/documents',
    path: '/admin/documents',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCircularsRoute =
  AuthenticatedAdminCircularsRouteImport.update({
    id: '/admin/circulars',
    path: '/admin/circulars',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAdsRoute = AuthenticatedAdminAdsRouteImport.update({
  id: '/admin/ads',
  path: '/admin/ads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminUsersUserIdRoute =
  AuthenticatedAdminUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedAdminUsersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/login-otp': typeof AuthLoginOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/catalog/$productId': typeof CatalogProductIdRoute
  '/u/$userCode': typeof UUserCodeRoute
  '/admin/ads': typeof AuthenticatedAdminAdsRoute
  '/admin/circulars': typeof AuthenticatedAdminCircularsRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/services/circulars': typeof AuthenticatedServicesCircularsRoute
  '/services/hs-codes': typeof AuthenticatedServicesHsCodesRoute
  '/trade/$id': typeof AuthenticatedTradeIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/support/': typeof AuthenticatedSupportIndexRoute
  '/trade/': typeof AuthenticatedTradeIndexRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/login-otp': typeof AuthLoginOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/catalog/$productId': typeof CatalogProductIdRoute
  '/u/$userCode': typeof UUserCodeRoute
  '/admin/ads': typeof AuthenticatedAdminAdsRoute
  '/admin/circulars': typeof AuthenticatedAdminCircularsRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/services/circulars': typeof AuthenticatedServicesCircularsRoute
  '/services/hs-codes': typeof AuthenticatedServicesHsCodesRoute
  '/trade/$id': typeof AuthenticatedTradeIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/support': typeof AuthenticatedSupportIndexRoute
  '/trade': typeof AuthenticatedTradeIndexRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/catalog': typeof CatalogRouteWithChildren
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/login-otp': typeof AuthLoginOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/catalog/$productId': typeof CatalogProductIdRoute
  '/u/$userCode': typeof UUserCodeRoute
  '/_authenticated/admin/ads': typeof AuthenticatedAdminAdsRoute
  '/_authenticated/admin/circulars': typeof AuthenticatedAdminCircularsRoute
  '/_authenticated/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/_authenticated/products/new': typeof AuthenticatedProductsNewRoute
  '/_authenticated/services/circulars': typeof AuthenticatedServicesCircularsRoute
  '/_authenticated/services/hs-codes': typeof AuthenticatedServicesHsCodesRoute
  '/_authenticated/trade/$id': typeof AuthenticatedTradeIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/support/': typeof AuthenticatedSupportIndexRoute
  '/_authenticated/trade/': typeof AuthenticatedTradeIndexRoute
  '/_authenticated/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/notifications'
    | '/auth/login'
    | '/auth/login-otp'
    | '/auth/register'
    | '/catalog/$productId'
    | '/u/$userCode'
    | '/admin/ads'
    | '/admin/circulars'
    | '/admin/documents'
    | '/admin/products'
    | '/admin/support'
    | '/admin/users'
    | '/products/new'
    | '/services/circulars'
    | '/services/hs-codes'
    | '/trade/$id'
    | '/admin/'
    | '/chat/'
    | '/dashboard/'
    | '/products/'
    | '/profile/'
    | '/support/'
    | '/trade/'
    | '/admin/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog'
    | '/notifications'
    | '/auth/login'
    | '/auth/login-otp'
    | '/auth/register'
    | '/catalog/$productId'
    | '/u/$userCode'
    | '/admin/ads'
    | '/admin/circulars'
    | '/admin/documents'
    | '/admin/products'
    | '/admin/support'
    | '/admin/users'
    | '/products/new'
    | '/services/circulars'
    | '/services/hs-codes'
    | '/trade/$id'
    | '/admin'
    | '/chat'
    | '/dashboard'
    | '/products'
    | '/profile'
    | '/support'
    | '/trade'
    | '/admin/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/catalog'
    | '/_authenticated/notifications'
    | '/auth/login'
    | '/auth/login-otp'
    | '/auth/register'
    | '/catalog/$productId'
    | '/u/$userCode'
    | '/_authenticated/admin/ads'
    | '/_authenticated/admin/circulars'
    | '/_authenticated/admin/documents'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/support'
    | '/_authenticated/admin/users'
    | '/_authenticated/products/new'
    | '/_authenticated/services/circulars'
    | '/_authenticated/services/hs-codes'
    | '/_authenticated/trade/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/chat/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/products/'
    | '/_authenticated/profile/'
    | '/_authenticated/support/'
    | '/_authenticated/trade/'
    | '/_authenticated/admin/users/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CatalogRoute: typeof CatalogRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLoginOtpRoute: typeof AuthLoginOtpRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  UUserCodeRoute: typeof UUserCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$userCode': {
      id: '/u/$userCode'
      path: '/u/$userCode'
      fullPath: '/u/$userCode'
      preLoaderRoute: typeof UUserCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/$productId': {
      id: '/catalog/$productId'
      path: '/$productId'
      fullPath: '/catalog/$productId'
      preLoaderRoute: typeof CatalogProductIdRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login-otp': {
      id: '/auth/login-otp'
      path: '/auth/login-otp'
      fullPath: '/auth/login-otp'
      preLoaderRoute: typeof AuthLoginOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trade/': {
      id: '/_authenticated/trade/'
      path: '/trade'
      fullPath: '/trade/'
      preLoaderRoute: typeof AuthenticatedTradeIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/support/': {
      id: '/_authenticated/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof AuthenticatedSupportIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trade/$id': {
      id: '/_authenticated/trade/$id'
      path: '/trade/$id'
      fullPath: '/trade/$id'
      preLoaderRoute: typeof AuthenticatedTradeIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/services/hs-codes': {
      id: '/_authenticated/services/hs-codes'
      path: '/services/hs-codes'
      fullPath: '/services/hs-codes'
      preLoaderRoute: typeof AuthenticatedServicesHsCodesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/services/circulars': {
      id: '/_authenticated/services/circulars'
      path: '/services/circulars'
      fullPath: '/services/circulars'
      preLoaderRoute: typeof AuthenticatedServicesCircularsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/new': {
      id: '/_authenticated/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthenticatedProductsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/documents': {
      id: '/_authenticated/admin/documents'
      path: '/admin/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AuthenticatedAdminDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/circulars': {
      id: '/_authenticated/admin/circulars'
      path: '/admin/circulars'
      fullPath: '/admin/circulars'
      preLoaderRoute: typeof AuthenticatedAdminCircularsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/ads': {
      id: '/_authenticated/admin/ads'
      path: '/admin/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AuthenticatedAdminAdsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users/$userId': {
      id: '/_authenticated/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminUsersRoute
    }
  }
}

interface AuthenticatedAdminUsersRouteChildren {
  AuthenticatedAdminUsersUserIdRoute: typeof AuthenticatedAdminUsersUserIdRoute
}

const AuthenticatedAdminUsersRouteChildren: AuthenticatedAdminUsersRouteChildren =
  {
    AuthenticatedAdminUsersUserIdRoute: AuthenticatedAdminUsersUserIdRoute,
  }

const AuthenticatedAdminUsersRouteWithChildren =
  AuthenticatedAdminUsersRoute._addFileChildren(
    AuthenticatedAdminUsersRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedAdminAdsRoute: typeof AuthenticatedAdminAdsRoute
  AuthenticatedAdminCircularsRoute: typeof AuthenticatedAdminCircularsRoute
  AuthenticatedAdminDocumentsRoute: typeof AuthenticatedAdminDocumentsRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRouteWithChildren
  AuthenticatedProductsNewRoute: typeof AuthenticatedProductsNewRoute
  AuthenticatedServicesCircularsRoute: typeof AuthenticatedServicesCircularsRoute
  AuthenticatedServicesHsCodesRoute: typeof AuthenticatedServicesHsCodesRoute
  AuthenticatedTradeIdRoute: typeof AuthenticatedTradeIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedSupportIndexRoute: typeof AuthenticatedSupportIndexRoute
  AuthenticatedTradeIndexRoute: typeof AuthenticatedTradeIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedAdminAdsRoute: AuthenticatedAdminAdsRoute,
  AuthenticatedAdminCircularsRoute: AuthenticatedAdminCircularsRoute,
  AuthenticatedAdminDocumentsRoute: AuthenticatedAdminDocumentsRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRouteWithChildren,
  AuthenticatedProductsNewRoute: AuthenticatedProductsNewRoute,
  AuthenticatedServicesCircularsRoute: AuthenticatedServicesCircularsRoute,
  AuthenticatedServicesHsCodesRoute: AuthenticatedServicesHsCodesRoute,
  AuthenticatedTradeIdRoute: AuthenticatedTradeIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedSupportIndexRoute: AuthenticatedSupportIndexRoute,
  AuthenticatedTradeIndexRoute: AuthenticatedTradeIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface CatalogRouteChildren {
  CatalogProductIdRoute: typeof CatalogProductIdRoute
}

const CatalogRouteChildren: CatalogRouteChildren = {
  CatalogProductIdRoute: CatalogProductIdRoute,
}

const CatalogRouteWithChildren =
  CatalogRoute._addFileChildren(CatalogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CatalogRoute: CatalogRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthLoginOtpRoute: AuthLoginOtpRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  UUserCodeRoute: UUserCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
