import React from 'react';
import ReactDOM from 'react-dom/client';
import { RouterProvider, createRouter } from '@tanstack/react-router';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';
import { HelmetProvider } from 'react-helmet-async';
import { routeTree } from './routeTree.gen.js'; // auto-generated by TanStack Router
import { trpc, createTRPCClient } from './trpc.js';
import { initSentry } from './sentry.js';
import { Toaster } from './components/ui/toaster.js';
import { useTranslation } from 'react-i18next';
import './styles/global.css';
import './i18n';

// ─── Init Sentry ──────────────────────────────────────────────────────────────

initSentry();

// ─── QueryClient ──────────────────────────────────────────────────────────────

const queryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: 60 * 1000, // 1 minute
      retry: 1,
    },
  },
});

// ─── tRPC Client ──────────────────────────────────────────────────────────────

const trpcClient = createTRPCClient();

// ─── Router ───────────────────────────────────────────────────────────────────

const router = createRouter({
  routeTree,
  context: { queryClient },
  defaultPreload: 'intent',
  defaultPreloadStaleTime: 0,
});

declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }
}

// ─── App ──────────────────────────────────────────────────────────────────────

function App() {
  const { i18n } = useTranslation();

  React.useEffect(() => {
    const language = ((i18n.resolvedLanguage ?? i18n.language ?? 'fa').split('-')[0] || 'fa') as string;
    const dir = language === 'en' ? 'ltr' : 'rtl';

    document.documentElement.lang = language;
    document.documentElement.dir = dir;
    document.body.dir = dir;
  }, [i18n.language, i18n.resolvedLanguage]);

  return (
    <HelmetProvider>
      <trpc.Provider client={trpcClient} queryClient={queryClient}>
        <QueryClientProvider client={queryClient}>
          <RouterProvider router={router} />
          <Toaster />
        </QueryClientProvider>
      </trpc.Provider>
    </HelmetProvider>
  );
}

const rootElement = document.getElementById('root')!;
ReactDOM.createRoot(rootElement).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
