/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NewsRouteImport } from './routes/news'
import { Route as MarketInsightsRouteImport } from './routes/market-insights'
import { Route as HarvestCalendarRouteImport } from './routes/harvest-calendar'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UUserCodeRouteImport } from './routes/u.$userCode'
import { Route as NewsNewsIdRouteImport } from './routes/news.$newsId'
import { Route as CatalogProductIdRouteImport } from './routes/catalog.$productId'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginOtpRouteImport } from './routes/auth/login-otp'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedDownloadsRouteImport } from './routes/_authenticated/downloads'
import { Route as AuthenticatedAdsRequestRouteImport } from './routes/_authenticated/ads-request'
import { Route as AuthenticatedTradeIndexRouteImport } from './routes/_authenticated/trade/index'
import { Route as AuthenticatedSupportIndexRouteImport } from './routes/_authenticated/support/index'
import { Route as AuthenticatedRfqIndexRouteImport } from './routes/_authenticated/rfq/index'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products/index'
import { Route as AuthenticatedMessagesIndexRouteImport } from './routes/_authenticated/messages/index'
import { Route as AuthenticatedMarketplaceIndexRouteImport } from './routes/_authenticated/marketplace/index'
import { Route as AuthenticatedMarketInsightsIndexRouteImport } from './routes/_authenticated/market-insights/index'
import { Route as AuthenticatedLicensesIndexRouteImport } from './routes/_authenticated/licenses/index'
import { Route as AuthenticatedHarvestIndexRouteImport } from './routes/_authenticated/harvest/index'
import { Route as AuthenticatedFinanceIndexRouteImport } from './routes/_authenticated/finance/index'
import { Route as AuthenticatedDocumentsIndexRouteImport } from './routes/_authenticated/documents/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat/index'
import { Route as AuthenticatedAiAdvisorIndexRouteImport } from './routes/_authenticated/ai-advisor/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedTradeIdRouteImport } from './routes/_authenticated/trade/$id'
import { Route as AuthenticatedServicesHsCodesRouteImport } from './routes/_authenticated/services/hs-codes'
import { Route as AuthenticatedServicesCircularsRouteImport } from './routes/_authenticated/services/circulars'
import { Route as AuthenticatedProductsNewRouteImport } from './routes/_authenticated/products/new'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTaxonomyRouteImport } from './routes/_authenticated/admin/taxonomy'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin/support'
import { Route as AuthenticatedAdminProductsRouteImport } from './routes/_authenticated/admin/products'
import { Route as AuthenticatedAdminNewsRouteImport } from './routes/_authenticated/admin/news'
import { Route as AuthenticatedAdminMarketRouteImport } from './routes/_authenticated/admin/market'
import { Route as AuthenticatedAdminHarvestRouteImport } from './routes/_authenticated/admin/harvest'
import { Route as AuthenticatedAdminDocumentsRouteImport } from './routes/_authenticated/admin/documents'
import { Route as AuthenticatedAdminCircularsRouteImport } from './routes/_authenticated/admin/circulars'
import { Route as AuthenticatedAdminAdsRouteImport } from './routes/_authenticated/admin/ads'
import { Route as AuthenticatedAdminAdminsRouteImport } from './routes/_authenticated/admin/admins'
import { Route as AuthenticatedAdminUsersUserIdRouteImport } from './routes/_authenticated/admin/users.$userId'

const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketInsightsRoute = MarketInsightsRouteImport.update({
  id: '/market-insights',
  path: '/market-insights',
  getParentRoute: () => rootRouteImport,
} as any)
const HarvestCalendarRoute = HarvestCalendarRouteImport.update({
  id: '/harvest-calendar',
  path: '/harvest-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UUserCodeRoute = UUserCodeRouteImport.update({
  id: '/u/$userCode',
  path: '/u/$userCode',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsNewsIdRoute = NewsNewsIdRouteImport.update({
  id: '/$newsId',
  path: '/$newsId',
  getParentRoute: () => NewsRoute,
} as any)
const CatalogProductIdRoute = CatalogProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => CatalogRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginOtpRoute = AuthLoginOtpRouteImport.update({
  id: '/auth/login-otp',
  path: '/auth/login-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDownloadsRoute = AuthenticatedDownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdsRequestRoute = AuthenticatedAdsRequestRouteImport.update({
  id: '/ads-request',
  path: '/ads-request',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTradeIndexRoute = AuthenticatedTradeIndexRouteImport.update({
  id: '/trade/',
  path: '/trade/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSupportIndexRoute =
  AuthenticatedSupportIndexRouteImport.update({
    id: '/support/',
    path: '/support/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRfqIndexRoute = AuthenticatedRfqIndexRouteImport.update({
  id: '/rfq/',
  path: '/rfq/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMessagesIndexRoute =
  AuthenticatedMessagesIndexRouteImport.update({
    id: '/messages/',
    path: '/messages/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarketplaceIndexRoute =
  AuthenticatedMarketplaceIndexRouteImport.update({
    id: '/marketplace/',
    path: '/marketplace/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarketInsightsIndexRoute =
  AuthenticatedMarketInsightsIndexRouteImport.update({
    id: '/market-insights/',
    path: '/market-insights/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLicensesIndexRoute =
  AuthenticatedLicensesIndexRouteImport.update({
    id: '/licenses/',
    path: '/licenses/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHarvestIndexRoute =
  AuthenticatedHarvestIndexRouteImport.update({
    id: '/harvest/',
    path: '/harvest/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceIndexRoute =
  AuthenticatedFinanceIndexRouteImport.update({
    id: '/finance/',
    path: '/finance/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDocumentsIndexRoute =
  AuthenticatedDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAiAdvisorIndexRoute =
  AuthenticatedAiAdvisorIndexRouteImport.update({
    id: '/ai-advisor/',
    path: '/ai-advisor/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTradeIdRoute = AuthenticatedTradeIdRouteImport.update({
  id: '/trade/$id',
  path: '/trade/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedServicesHsCodesRoute =
  AuthenticatedServicesHsCodesRouteImport.update({
    id: '/services/hs-codes',
    path: '/services/hs-codes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedServicesCircularsRoute =
  AuthenticatedServicesCircularsRouteImport.update({
    id: '/services/circulars',
    path: '/services/circulars',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsNewRoute =
  AuthenticatedProductsNewRouteImport.update({
    id: '/products/new',
    path: '/products/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminTaxonomyRoute =
  AuthenticatedAdminTaxonomyRouteImport.update({
    id: '/admin/taxonomy',
    path: '/admin/taxonomy',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/admin/support',
    path: '/admin/support',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminProductsRoute =
  AuthenticatedAdminProductsRouteImport.update({
    id: '/admin/products',
    path: '/admin/products',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminNewsRoute = AuthenticatedAdminNewsRouteImport.update({
  id: '/admin/news',
  path: '/admin/news',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminMarketRoute =
  AuthenticatedAdminMarketRouteImport.update({
    id: '/admin/market',
    path: '/admin/market',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminHarvestRoute =
  AuthenticatedAdminHarvestRouteImport.update({
    id: '/admin/harvest',
    path: '/admin/harvest',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDocumentsRoute =
  AuthenticatedAdminDocumentsRouteImport.update({
    id: '/admin/documents',
    path: '/admin/documents',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCircularsRoute =
  AuthenticatedAdminCircularsRouteImport.update({
    id: '/admin/circulars',
    path: '/admin/circulars',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminAdsRoute = AuthenticatedAdminAdsRouteImport.update({
  id: '/admin/ads',
  path: '/admin/ads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminAdminsRoute =
  AuthenticatedAdminAdminsRouteImport.update({
    id: '/admin/admins',
    path: '/admin/admins',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersUserIdRoute =
  AuthenticatedAdminUsersUserIdRouteImport.update({
    id: '/$userId',
    path: '/$userId',
    getParentRoute: () => AuthenticatedAdminUsersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/contact': typeof ContactRoute
  '/harvest-calendar': typeof HarvestCalendarRoute
  '/market-insights': typeof MarketInsightsRoute
  '/news': typeof NewsRouteWithChildren
  '/ads-request': typeof AuthenticatedAdsRequestRoute
  '/downloads': typeof AuthenticatedDownloadsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/login-otp': typeof AuthLoginOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/catalog/$productId': typeof CatalogProductIdRoute
  '/news/$newsId': typeof NewsNewsIdRoute
  '/u/$userCode': typeof UUserCodeRoute
  '/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/admin/ads': typeof AuthenticatedAdminAdsRoute
  '/admin/circulars': typeof AuthenticatedAdminCircularsRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/harvest': typeof AuthenticatedAdminHarvestRoute
  '/admin/market': typeof AuthenticatedAdminMarketRoute
  '/admin/news': typeof AuthenticatedAdminNewsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/taxonomy': typeof AuthenticatedAdminTaxonomyRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/services/circulars': typeof AuthenticatedServicesCircularsRoute
  '/services/hs-codes': typeof AuthenticatedServicesHsCodesRoute
  '/trade/$id': typeof AuthenticatedTradeIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/ai-advisor/': typeof AuthenticatedAiAdvisorIndexRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/finance/': typeof AuthenticatedFinanceIndexRoute
  '/harvest/': typeof AuthenticatedHarvestIndexRoute
  '/licenses/': typeof AuthenticatedLicensesIndexRoute
  '/market-insights/': typeof AuthenticatedMarketInsightsIndexRoute
  '/marketplace/': typeof AuthenticatedMarketplaceIndexRoute
  '/messages/': typeof AuthenticatedMessagesIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/rfq/': typeof AuthenticatedRfqIndexRoute
  '/support/': typeof AuthenticatedSupportIndexRoute
  '/trade/': typeof AuthenticatedTradeIndexRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/contact': typeof ContactRoute
  '/harvest-calendar': typeof HarvestCalendarRoute
  '/market-insights': typeof AuthenticatedMarketInsightsIndexRoute
  '/news': typeof NewsRouteWithChildren
  '/ads-request': typeof AuthenticatedAdsRequestRoute
  '/downloads': typeof AuthenticatedDownloadsRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/login-otp': typeof AuthLoginOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/catalog/$productId': typeof CatalogProductIdRoute
  '/news/$newsId': typeof NewsNewsIdRoute
  '/u/$userCode': typeof UUserCodeRoute
  '/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/admin/ads': typeof AuthenticatedAdminAdsRoute
  '/admin/circulars': typeof AuthenticatedAdminCircularsRoute
  '/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/admin/harvest': typeof AuthenticatedAdminHarvestRoute
  '/admin/market': typeof AuthenticatedAdminMarketRoute
  '/admin/news': typeof AuthenticatedAdminNewsRoute
  '/admin/products': typeof AuthenticatedAdminProductsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/taxonomy': typeof AuthenticatedAdminTaxonomyRoute
  '/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/services/circulars': typeof AuthenticatedServicesCircularsRoute
  '/services/hs-codes': typeof AuthenticatedServicesHsCodesRoute
  '/trade/$id': typeof AuthenticatedTradeIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/ai-advisor': typeof AuthenticatedAiAdvisorIndexRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/documents': typeof AuthenticatedDocumentsIndexRoute
  '/finance': typeof AuthenticatedFinanceIndexRoute
  '/harvest': typeof AuthenticatedHarvestIndexRoute
  '/licenses': typeof AuthenticatedLicensesIndexRoute
  '/marketplace': typeof AuthenticatedMarketplaceIndexRoute
  '/messages': typeof AuthenticatedMessagesIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/rfq': typeof AuthenticatedRfqIndexRoute
  '/support': typeof AuthenticatedSupportIndexRoute
  '/trade': typeof AuthenticatedTradeIndexRoute
  '/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/catalog': typeof CatalogRouteWithChildren
  '/contact': typeof ContactRoute
  '/harvest-calendar': typeof HarvestCalendarRoute
  '/market-insights': typeof MarketInsightsRoute
  '/news': typeof NewsRouteWithChildren
  '/_authenticated/ads-request': typeof AuthenticatedAdsRequestRoute
  '/_authenticated/downloads': typeof AuthenticatedDownloadsRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/login-otp': typeof AuthLoginOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/catalog/$productId': typeof CatalogProductIdRoute
  '/news/$newsId': typeof NewsNewsIdRoute
  '/u/$userCode': typeof UUserCodeRoute
  '/_authenticated/admin/admins': typeof AuthenticatedAdminAdminsRoute
  '/_authenticated/admin/ads': typeof AuthenticatedAdminAdsRoute
  '/_authenticated/admin/circulars': typeof AuthenticatedAdminCircularsRoute
  '/_authenticated/admin/documents': typeof AuthenticatedAdminDocumentsRoute
  '/_authenticated/admin/harvest': typeof AuthenticatedAdminHarvestRoute
  '/_authenticated/admin/market': typeof AuthenticatedAdminMarketRoute
  '/_authenticated/admin/news': typeof AuthenticatedAdminNewsRoute
  '/_authenticated/admin/products': typeof AuthenticatedAdminProductsRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/admin/taxonomy': typeof AuthenticatedAdminTaxonomyRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRouteWithChildren
  '/_authenticated/products/new': typeof AuthenticatedProductsNewRoute
  '/_authenticated/services/circulars': typeof AuthenticatedServicesCircularsRoute
  '/_authenticated/services/hs-codes': typeof AuthenticatedServicesHsCodesRoute
  '/_authenticated/trade/$id': typeof AuthenticatedTradeIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/ai-advisor/': typeof AuthenticatedAiAdvisorIndexRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/documents/': typeof AuthenticatedDocumentsIndexRoute
  '/_authenticated/finance/': typeof AuthenticatedFinanceIndexRoute
  '/_authenticated/harvest/': typeof AuthenticatedHarvestIndexRoute
  '/_authenticated/licenses/': typeof AuthenticatedLicensesIndexRoute
  '/_authenticated/market-insights/': typeof AuthenticatedMarketInsightsIndexRoute
  '/_authenticated/marketplace/': typeof AuthenticatedMarketplaceIndexRoute
  '/_authenticated/messages/': typeof AuthenticatedMessagesIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/rfq/': typeof AuthenticatedRfqIndexRoute
  '/_authenticated/support/': typeof AuthenticatedSupportIndexRoute
  '/_authenticated/trade/': typeof AuthenticatedTradeIndexRoute
  '/_authenticated/admin/users/$userId': typeof AuthenticatedAdminUsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/catalog'
    | '/contact'
    | '/harvest-calendar'
    | '/market-insights'
    | '/news'
    | '/ads-request'
    | '/downloads'
    | '/notifications'
    | '/auth/login'
    | '/auth/login-otp'
    | '/auth/register'
    | '/catalog/$productId'
    | '/news/$newsId'
    | '/u/$userCode'
    | '/admin/admins'
    | '/admin/ads'
    | '/admin/circulars'
    | '/admin/documents'
    | '/admin/harvest'
    | '/admin/market'
    | '/admin/news'
    | '/admin/products'
    | '/admin/support'
    | '/admin/taxonomy'
    | '/admin/users'
    | '/products/new'
    | '/services/circulars'
    | '/services/hs-codes'
    | '/trade/$id'
    | '/admin/'
    | '/ai-advisor/'
    | '/chat/'
    | '/dashboard/'
    | '/documents/'
    | '/finance/'
    | '/harvest/'
    | '/licenses/'
    | '/market-insights/'
    | '/marketplace/'
    | '/messages/'
    | '/products/'
    | '/profile/'
    | '/rfq/'
    | '/support/'
    | '/trade/'
    | '/admin/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/catalog'
    | '/contact'
    | '/harvest-calendar'
    | '/market-insights'
    | '/news'
    | '/ads-request'
    | '/downloads'
    | '/notifications'
    | '/auth/login'
    | '/auth/login-otp'
    | '/auth/register'
    | '/catalog/$productId'
    | '/news/$newsId'
    | '/u/$userCode'
    | '/admin/admins'
    | '/admin/ads'
    | '/admin/circulars'
    | '/admin/documents'
    | '/admin/harvest'
    | '/admin/market'
    | '/admin/news'
    | '/admin/products'
    | '/admin/support'
    | '/admin/taxonomy'
    | '/admin/users'
    | '/products/new'
    | '/services/circulars'
    | '/services/hs-codes'
    | '/trade/$id'
    | '/admin'
    | '/ai-advisor'
    | '/chat'
    | '/dashboard'
    | '/documents'
    | '/finance'
    | '/harvest'
    | '/licenses'
    | '/marketplace'
    | '/messages'
    | '/products'
    | '/profile'
    | '/rfq'
    | '/support'
    | '/trade'
    | '/admin/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/catalog'
    | '/contact'
    | '/harvest-calendar'
    | '/market-insights'
    | '/news'
    | '/_authenticated/ads-request'
    | '/_authenticated/downloads'
    | '/_authenticated/notifications'
    | '/auth/login'
    | '/auth/login-otp'
    | '/auth/register'
    | '/catalog/$productId'
    | '/news/$newsId'
    | '/u/$userCode'
    | '/_authenticated/admin/admins'
    | '/_authenticated/admin/ads'
    | '/_authenticated/admin/circulars'
    | '/_authenticated/admin/documents'
    | '/_authenticated/admin/harvest'
    | '/_authenticated/admin/market'
    | '/_authenticated/admin/news'
    | '/_authenticated/admin/products'
    | '/_authenticated/admin/support'
    | '/_authenticated/admin/taxonomy'
    | '/_authenticated/admin/users'
    | '/_authenticated/products/new'
    | '/_authenticated/services/circulars'
    | '/_authenticated/services/hs-codes'
    | '/_authenticated/trade/$id'
    | '/_authenticated/admin/'
    | '/_authenticated/ai-advisor/'
    | '/_authenticated/chat/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/documents/'
    | '/_authenticated/finance/'
    | '/_authenticated/harvest/'
    | '/_authenticated/licenses/'
    | '/_authenticated/market-insights/'
    | '/_authenticated/marketplace/'
    | '/_authenticated/messages/'
    | '/_authenticated/products/'
    | '/_authenticated/profile/'
    | '/_authenticated/rfq/'
    | '/_authenticated/support/'
    | '/_authenticated/trade/'
    | '/_authenticated/admin/users/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  CatalogRoute: typeof CatalogRouteWithChildren
  ContactRoute: typeof ContactRoute
  HarvestCalendarRoute: typeof HarvestCalendarRoute
  MarketInsightsRoute: typeof MarketInsightsRoute
  NewsRoute: typeof NewsRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthLoginOtpRoute: typeof AuthLoginOtpRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  UUserCodeRoute: typeof UUserCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-insights': {
      id: '/market-insights'
      path: '/market-insights'
      fullPath: '/market-insights'
      preLoaderRoute: typeof MarketInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/harvest-calendar': {
      id: '/harvest-calendar'
      path: '/harvest-calendar'
      fullPath: '/harvest-calendar'
      preLoaderRoute: typeof HarvestCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$userCode': {
      id: '/u/$userCode'
      path: '/u/$userCode'
      fullPath: '/u/$userCode'
      preLoaderRoute: typeof UUserCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$newsId': {
      id: '/news/$newsId'
      path: '/$newsId'
      fullPath: '/news/$newsId'
      preLoaderRoute: typeof NewsNewsIdRouteImport
      parentRoute: typeof NewsRoute
    }
    '/catalog/$productId': {
      id: '/catalog/$productId'
      path: '/$productId'
      fullPath: '/catalog/$productId'
      preLoaderRoute: typeof CatalogProductIdRouteImport
      parentRoute: typeof CatalogRoute
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login-otp': {
      id: '/auth/login-otp'
      path: '/auth/login-otp'
      fullPath: '/auth/login-otp'
      preLoaderRoute: typeof AuthLoginOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/downloads': {
      id: '/_authenticated/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof AuthenticatedDownloadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ads-request': {
      id: '/_authenticated/ads-request'
      path: '/ads-request'
      fullPath: '/ads-request'
      preLoaderRoute: typeof AuthenticatedAdsRequestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trade/': {
      id: '/_authenticated/trade/'
      path: '/trade'
      fullPath: '/trade/'
      preLoaderRoute: typeof AuthenticatedTradeIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/support/': {
      id: '/_authenticated/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof AuthenticatedSupportIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rfq/': {
      id: '/_authenticated/rfq/'
      path: '/rfq'
      fullPath: '/rfq/'
      preLoaderRoute: typeof AuthenticatedRfqIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/messages/': {
      id: '/_authenticated/messages/'
      path: '/messages'
      fullPath: '/messages/'
      preLoaderRoute: typeof AuthenticatedMessagesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketplace/': {
      id: '/_authenticated/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof AuthenticatedMarketplaceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/market-insights/': {
      id: '/_authenticated/market-insights/'
      path: '/market-insights'
      fullPath: '/market-insights/'
      preLoaderRoute: typeof AuthenticatedMarketInsightsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/licenses/': {
      id: '/_authenticated/licenses/'
      path: '/licenses'
      fullPath: '/licenses/'
      preLoaderRoute: typeof AuthenticatedLicensesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/harvest/': {
      id: '/_authenticated/harvest/'
      path: '/harvest'
      fullPath: '/harvest/'
      preLoaderRoute: typeof AuthenticatedHarvestIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance/': {
      id: '/_authenticated/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof AuthenticatedFinanceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/documents/': {
      id: '/_authenticated/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof AuthenticatedDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai-advisor/': {
      id: '/_authenticated/ai-advisor/'
      path: '/ai-advisor'
      fullPath: '/ai-advisor/'
      preLoaderRoute: typeof AuthenticatedAiAdvisorIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trade/$id': {
      id: '/_authenticated/trade/$id'
      path: '/trade/$id'
      fullPath: '/trade/$id'
      preLoaderRoute: typeof AuthenticatedTradeIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/services/hs-codes': {
      id: '/_authenticated/services/hs-codes'
      path: '/services/hs-codes'
      fullPath: '/services/hs-codes'
      preLoaderRoute: typeof AuthenticatedServicesHsCodesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/services/circulars': {
      id: '/_authenticated/services/circulars'
      path: '/services/circulars'
      fullPath: '/services/circulars'
      preLoaderRoute: typeof AuthenticatedServicesCircularsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/new': {
      id: '/_authenticated/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthenticatedProductsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/taxonomy': {
      id: '/_authenticated/admin/taxonomy'
      path: '/admin/taxonomy'
      fullPath: '/admin/taxonomy'
      preLoaderRoute: typeof AuthenticatedAdminTaxonomyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/admin/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/products': {
      id: '/_authenticated/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AuthenticatedAdminProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/news': {
      id: '/_authenticated/admin/news'
      path: '/admin/news'
      fullPath: '/admin/news'
      preLoaderRoute: typeof AuthenticatedAdminNewsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/market': {
      id: '/_authenticated/admin/market'
      path: '/admin/market'
      fullPath: '/admin/market'
      preLoaderRoute: typeof AuthenticatedAdminMarketRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/harvest': {
      id: '/_authenticated/admin/harvest'
      path: '/admin/harvest'
      fullPath: '/admin/harvest'
      preLoaderRoute: typeof AuthenticatedAdminHarvestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/documents': {
      id: '/_authenticated/admin/documents'
      path: '/admin/documents'
      fullPath: '/admin/documents'
      preLoaderRoute: typeof AuthenticatedAdminDocumentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/circulars': {
      id: '/_authenticated/admin/circulars'
      path: '/admin/circulars'
      fullPath: '/admin/circulars'
      preLoaderRoute: typeof AuthenticatedAdminCircularsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/ads': {
      id: '/_authenticated/admin/ads'
      path: '/admin/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AuthenticatedAdminAdsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/admins': {
      id: '/_authenticated/admin/admins'
      path: '/admin/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AuthenticatedAdminAdminsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users/$userId': {
      id: '/_authenticated/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AuthenticatedAdminUsersUserIdRouteImport
      parentRoute: typeof AuthenticatedAdminUsersRoute
    }
  }
}

interface AuthenticatedAdminUsersRouteChildren {
  AuthenticatedAdminUsersUserIdRoute: typeof AuthenticatedAdminUsersUserIdRoute
}

const AuthenticatedAdminUsersRouteChildren: AuthenticatedAdminUsersRouteChildren =
  {
    AuthenticatedAdminUsersUserIdRoute: AuthenticatedAdminUsersUserIdRoute,
  }

const AuthenticatedAdminUsersRouteWithChildren =
  AuthenticatedAdminUsersRoute._addFileChildren(
    AuthenticatedAdminUsersRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdsRequestRoute: typeof AuthenticatedAdsRequestRoute
  AuthenticatedDownloadsRoute: typeof AuthenticatedDownloadsRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedAdminAdminsRoute: typeof AuthenticatedAdminAdminsRoute
  AuthenticatedAdminAdsRoute: typeof AuthenticatedAdminAdsRoute
  AuthenticatedAdminCircularsRoute: typeof AuthenticatedAdminCircularsRoute
  AuthenticatedAdminDocumentsRoute: typeof AuthenticatedAdminDocumentsRoute
  AuthenticatedAdminHarvestRoute: typeof AuthenticatedAdminHarvestRoute
  AuthenticatedAdminMarketRoute: typeof AuthenticatedAdminMarketRoute
  AuthenticatedAdminNewsRoute: typeof AuthenticatedAdminNewsRoute
  AuthenticatedAdminProductsRoute: typeof AuthenticatedAdminProductsRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminTaxonomyRoute: typeof AuthenticatedAdminTaxonomyRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRouteWithChildren
  AuthenticatedProductsNewRoute: typeof AuthenticatedProductsNewRoute
  AuthenticatedServicesCircularsRoute: typeof AuthenticatedServicesCircularsRoute
  AuthenticatedServicesHsCodesRoute: typeof AuthenticatedServicesHsCodesRoute
  AuthenticatedTradeIdRoute: typeof AuthenticatedTradeIdRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAiAdvisorIndexRoute: typeof AuthenticatedAiAdvisorIndexRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedDocumentsIndexRoute: typeof AuthenticatedDocumentsIndexRoute
  AuthenticatedFinanceIndexRoute: typeof AuthenticatedFinanceIndexRoute
  AuthenticatedHarvestIndexRoute: typeof AuthenticatedHarvestIndexRoute
  AuthenticatedLicensesIndexRoute: typeof AuthenticatedLicensesIndexRoute
  AuthenticatedMarketInsightsIndexRoute: typeof AuthenticatedMarketInsightsIndexRoute
  AuthenticatedMarketplaceIndexRoute: typeof AuthenticatedMarketplaceIndexRoute
  AuthenticatedMessagesIndexRoute: typeof AuthenticatedMessagesIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedRfqIndexRoute: typeof AuthenticatedRfqIndexRoute
  AuthenticatedSupportIndexRoute: typeof AuthenticatedSupportIndexRoute
  AuthenticatedTradeIndexRoute: typeof AuthenticatedTradeIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdsRequestRoute: AuthenticatedAdsRequestRoute,
  AuthenticatedDownloadsRoute: AuthenticatedDownloadsRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedAdminAdminsRoute: AuthenticatedAdminAdminsRoute,
  AuthenticatedAdminAdsRoute: AuthenticatedAdminAdsRoute,
  AuthenticatedAdminCircularsRoute: AuthenticatedAdminCircularsRoute,
  AuthenticatedAdminDocumentsRoute: AuthenticatedAdminDocumentsRoute,
  AuthenticatedAdminHarvestRoute: AuthenticatedAdminHarvestRoute,
  AuthenticatedAdminMarketRoute: AuthenticatedAdminMarketRoute,
  AuthenticatedAdminNewsRoute: AuthenticatedAdminNewsRoute,
  AuthenticatedAdminProductsRoute: AuthenticatedAdminProductsRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
  AuthenticatedAdminTaxonomyRoute: AuthenticatedAdminTaxonomyRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRouteWithChildren,
  AuthenticatedProductsNewRoute: AuthenticatedProductsNewRoute,
  AuthenticatedServicesCircularsRoute: AuthenticatedServicesCircularsRoute,
  AuthenticatedServicesHsCodesRoute: AuthenticatedServicesHsCodesRoute,
  AuthenticatedTradeIdRoute: AuthenticatedTradeIdRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAiAdvisorIndexRoute: AuthenticatedAiAdvisorIndexRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedDocumentsIndexRoute: AuthenticatedDocumentsIndexRoute,
  AuthenticatedFinanceIndexRoute: AuthenticatedFinanceIndexRoute,
  AuthenticatedHarvestIndexRoute: AuthenticatedHarvestIndexRoute,
  AuthenticatedLicensesIndexRoute: AuthenticatedLicensesIndexRoute,
  AuthenticatedMarketInsightsIndexRoute: AuthenticatedMarketInsightsIndexRoute,
  AuthenticatedMarketplaceIndexRoute: AuthenticatedMarketplaceIndexRoute,
  AuthenticatedMessagesIndexRoute: AuthenticatedMessagesIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedRfqIndexRoute: AuthenticatedRfqIndexRoute,
  AuthenticatedSupportIndexRoute: AuthenticatedSupportIndexRoute,
  AuthenticatedTradeIndexRoute: AuthenticatedTradeIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface CatalogRouteChildren {
  CatalogProductIdRoute: typeof CatalogProductIdRoute
}

const CatalogRouteChildren: CatalogRouteChildren = {
  CatalogProductIdRoute: CatalogProductIdRoute,
}

const CatalogRouteWithChildren =
  CatalogRoute._addFileChildren(CatalogRouteChildren)

interface NewsRouteChildren {
  NewsNewsIdRoute: typeof NewsNewsIdRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsNewsIdRoute: NewsNewsIdRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  CatalogRoute: CatalogRouteWithChildren,
  ContactRoute: ContactRoute,
  HarvestCalendarRoute: HarvestCalendarRoute,
  MarketInsightsRoute: MarketInsightsRoute,
  NewsRoute: NewsRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthLoginOtpRoute: AuthLoginOtpRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  UUserCodeRoute: UUserCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
