
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  objectEnumValues,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('@prisma/client/runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 6.19.2
 * Query Engine version: c2990dca591cba766e3b7ef5d9e8a84796e47ab7
 */
Prisma.prismaVersion = {
  client: "6.19.2",
  engine: "c2990dca591cba766e3b7ef5d9e8a84796e47ab7"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = objectEnumValues.instances.DbNull
Prisma.JsonNull = objectEnumValues.instances.JsonNull
Prisma.AnyNull = objectEnumValues.instances.AnyNull

Prisma.NullTypes = {
  DbNull: objectEnumValues.classes.DbNull,
  JsonNull: objectEnumValues.classes.JsonNull,
  AnyNull: objectEnumValues.classes.AnyNull
}



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.UserScalarFieldEnum = {
  id: 'id',
  userCode: 'userCode',
  membershipType: 'membershipType',
  role: 'role',
  status: 'status',
  nationalCode: 'nationalCode',
  nationalId: 'nationalId',
  mobile: 'mobile',
  email: 'email',
  passwordHash: 'passwordHash',
  lastLoginAt: 'lastLoginAt',
  loginAttempts: 'loginAttempts',
  lockedUntil: 'lockedUntil',
  agreedToTerms: 'agreedToTerms',
  agreedToTermsAt: 'agreedToTermsAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AdminProfileScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  adminRole: 'adminRole',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.OtpCodeScalarFieldEnum = {
  id: 'id',
  mobile: 'mobile',
  code: 'code',
  purpose: 'purpose',
  expiresAt: 'expiresAt',
  usedAt: 'usedAt',
  createdAt: 'createdAt'
};

exports.Prisma.RefreshTokenScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  tokenHash: 'tokenHash',
  expiresAt: 'expiresAt',
  revokedAt: 'revokedAt',
  userAgent: 'userAgent',
  ipAddress: 'ipAddress',
  createdAt: 'createdAt'
};

exports.Prisma.UserProfileScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  companyName: 'companyName',
  unitName: 'unitName',
  unitType: 'unitType',
  guildCode: 'guildCode',
  businessId: 'businessId',
  producedGoods: 'producedGoods',
  productIdNumber: 'productIdNumber',
  singleProduct: 'singleProduct',
  phone: 'phone',
  fax: 'fax',
  website: 'website',
  province: 'province',
  city: 'city',
  addressLine: 'addressLine',
  postalCode: 'postalCode',
  activityType: 'activityType',
  commodityGroup: 'commodityGroup',
  position: 'position',
  experienceYears: 'experienceYears',
  description: 'description',
  passportNumber: 'passportNumber',
  passportExpiryDate: 'passportExpiryDate',
  verificationStatus: 'verificationStatus',
  verifiedAt: 'verifiedAt',
  verifiedById: 'verifiedById',
  rejectionReason: 'rejectionReason',
  membershipGrade: 'membershipGrade',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DocumentScalarFieldEnum = {
  id: 'id',
  profileId: 'profileId',
  type: 'type',
  fileName: 'fileName',
  fileKey: 'fileKey',
  fileSize: 'fileSize',
  mimeType: 'mimeType',
  status: 'status',
  verifiedAt: 'verifiedAt',
  verifiedById: 'verifiedById',
  rejectionReason: 'rejectionReason',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  nameFa: 'nameFa',
  nameEn: 'nameEn',
  grade: 'grade',
  serviceCode: 'serviceCode',
  hsCode: 'hsCode',
  isicCode: 'isicCode',
  commodityGroup: 'commodityGroup',
  origin: 'origin',
  countryOfOrigin: 'countryOfOrigin',
  technicalSpecs: 'technicalSpecs',
  standardNumber: 'standardNumber',
  description: 'description',
  packagingType: 'packagingType',
  weightKg: 'weightKg',
  lengthCm: 'lengthCm',
  widthCm: 'widthCm',
  heightCm: 'heightCm',
  weightUnit: 'weightUnit',
  deliveryTerms: 'deliveryTerms',
  deliveryLocation: 'deliveryLocation',
  minOrderQuantity: 'minOrderQuantity',
  preparationTimeDays: 'preparationTimeDays',
  paymentMethod: 'paymentMethod',
  advancePercent: 'advancePercent',
  onDeliveryPercent: 'onDeliveryPercent',
  productionDate: 'productionDate',
  expiryDate: 'expiryDate',
  isAvailableInStock: 'isAvailableInStock',
  isApproved: 'isApproved',
  approvedAt: 'approvedAt',
  approvedById: 'approvedById',
  rejectionReason: 'rejectionReason',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProductMediaScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  type: 'type',
  fileKey: 'fileKey',
  thumbnailKey: 'thumbnailKey',
  fileName: 'fileName',
  fileSize: 'fileSize',
  mimeType: 'mimeType',
  sortOrder: 'sortOrder',
  isMain: 'isMain',
  createdAt: 'createdAt'
};

exports.Prisma.TradeRequestScalarFieldEnum = {
  id: 'id',
  requesterId: 'requesterId',
  type: 'type',
  status: 'status',
  productId: 'productId',
  productNameFa: 'productNameFa',
  productNameEn: 'productNameEn',
  serviceCode: 'serviceCode',
  hsCode: 'hsCode',
  commodityGroup: 'commodityGroup',
  supplySourceType: 'supplySourceType',
  supplySourceName: 'supplySourceName',
  quantity: 'quantity',
  targetPrice: 'targetPrice',
  currency: 'currency',
  deliveryLocation: 'deliveryLocation',
  notes: 'notes',
  matchedWithId: 'matchedWithId',
  matchedAt: 'matchedAt',
  matchedBy: 'matchedBy',
  expiresAt: 'expiresAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.TradeAttachmentScalarFieldEnum = {
  id: 'id',
  tradeRequestId: 'tradeRequestId',
  fileKey: 'fileKey',
  fileName: 'fileName',
  fileSize: 'fileSize',
  mimeType: 'mimeType',
  createdAt: 'createdAt'
};

exports.Prisma.HsCodeScalarFieldEnum = {
  id: 'id',
  code: 'code',
  descriptionFa: 'descriptionFa',
  descriptionEn: 'descriptionEn',
  parentCode: 'parentCode',
  level: 'level'
};

exports.Prisma.IsicCodeScalarFieldEnum = {
  id: 'id',
  code: 'code',
  descriptionFa: 'descriptionFa',
  descriptionEn: 'descriptionEn',
  section: 'section',
  division: 'division'
};

exports.Prisma.CircularScalarFieldEnum = {
  id: 'id',
  title: 'title',
  content: 'content',
  summary: 'summary',
  fileKey: 'fileKey',
  publishedAt: 'publishedAt',
  isPublished: 'isPublished',
  authorId: 'authorId',
  tags: 'tags',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.DownloadItemScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  fileKey: 'fileKey',
  fileName: 'fileName',
  fileSize: 'fileSize',
  mimeType: 'mimeType',
  category: 'category',
  sortOrder: 'sortOrder',
  isActive: 'isActive',
  downloadCount: 'downloadCount',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AdvertisementScalarFieldEnum = {
  id: 'id',
  requesterId: 'requesterId',
  title: 'title',
  description: 'description',
  fileKey: 'fileKey',
  targetUrl: 'targetUrl',
  adType: 'adType',
  status: 'status',
  startDate: 'startDate',
  endDate: 'endDate',
  reviewedAt: 'reviewedAt',
  reviewedById: 'reviewedById',
  rejectionReason: 'rejectionReason',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SupportTicketScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  subject: 'subject',
  category: 'category',
  status: 'status',
  assignedTo: 'assignedTo',
  resolvedAt: 'resolvedAt',
  closedAt: 'closedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SupportMessageScalarFieldEnum = {
  id: 'id',
  ticketId: 'ticketId',
  senderId: 'senderId',
  senderType: 'senderType',
  content: 'content',
  attachmentKey: 'attachmentKey',
  createdAt: 'createdAt'
};

exports.Prisma.AiConversationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  title: 'title',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AiMessageScalarFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  role: 'role',
  content: 'content',
  tokens: 'tokens',
  createdAt: 'createdAt'
};

exports.Prisma.AnalysisRequestScalarFieldEnum = {
  id: 'id',
  requesterId: 'requesterId',
  subject: 'subject',
  consultationCategory: 'consultationCategory',
  commodityGroup: 'commodityGroup',
  targetMarket: 'targetMarket',
  description: 'description',
  status: 'status',
  assignedToId: 'assignedToId',
  resultFileKey: 'resultFileKey',
  notes: 'notes',
  completedAt: 'completedAt',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.NewsScalarFieldEnum = {
  id: 'id',
  title: 'title',
  summary: 'summary',
  content: 'content',
  imageKey: 'imageKey',
  sourceUrl: 'sourceUrl',
  sourceName: 'sourceName',
  category: 'category',
  tags: 'tags',
  isPublished: 'isPublished',
  publishedAt: 'publishedAt',
  authorId: 'authorId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.NewsletterSubscriptionScalarFieldEnum = {
  id: 'id',
  email: 'email',
  name: 'name',
  isActive: 'isActive',
  createdAt: 'createdAt',
  unsubscribedAt: 'unsubscribedAt'
};

exports.Prisma.SurveyScalarFieldEnum = {
  id: 'id',
  title: 'title',
  description: 'description',
  questions: 'questions',
  isActive: 'isActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SurveyResponseScalarFieldEnum = {
  id: 'id',
  surveyId: 'surveyId',
  respondentEmail: 'respondentEmail',
  answers: 'answers',
  createdAt: 'createdAt'
};

exports.Prisma.ContactMessageScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  phone: 'phone',
  subject: 'subject',
  message: 'message',
  isRead: 'isRead',
  readAt: 'readAt',
  createdAt: 'createdAt'
};

exports.Prisma.ConversationScalarFieldEnum = {
  id: 'id',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  lastMessageId: 'lastMessageId'
};

exports.Prisma.ConversationParticipantScalarFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  userId: 'userId',
  joinedAt: 'joinedAt'
};

exports.Prisma.MessageScalarFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  senderId: 'senderId',
  content: 'content',
  isRead: 'isRead',
  readAt: 'readAt',
  createdAt: 'createdAt'
};

exports.Prisma.NotificationScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  type: 'type',
  title: 'title',
  message: 'message',
  data: 'data',
  isRead: 'isRead',
  readAt: 'readAt',
  link: 'link',
  createdAt: 'createdAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.MembershipType = exports.$Enums.MembershipType = {
  INDIVIDUAL: 'INDIVIDUAL',
  LEGAL: 'LEGAL',
  GUILD_MEMBER: 'GUILD_MEMBER'
};

exports.UserRole = exports.$Enums.UserRole = {
  TRADER: 'TRADER',
  PRODUCER: 'PRODUCER',
  KNOWLEDGE_BASED: 'KNOWLEDGE_BASED',
  WHOLESALER: 'WHOLESALER',
  BROKER: 'BROKER',
  INTERMEDIARY: 'INTERMEDIARY',
  GUILD: 'GUILD',
  FARMER: 'FARMER',
  INVESTOR: 'INVESTOR'
};

exports.UserStatus = exports.$Enums.UserStatus = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  SUSPENDED: 'SUSPENDED',
  REJECTED: 'REJECTED'
};

exports.AdminRole = exports.$Enums.AdminRole = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  MEDIA_SUPERVISOR: 'MEDIA_SUPERVISOR',
  EXPERT: 'EXPERT',
  ANALYST: 'ANALYST'
};

exports.CommodityGroup = exports.$Enums.CommodityGroup = {
  INDUSTRIAL: 'INDUSTRIAL',
  CHEMICAL: 'CHEMICAL',
  TELECOM: 'TELECOM',
  METAL: 'METAL',
  FOOD: 'FOOD',
  TEXTILE: 'TEXTILE',
  AGRICULTURAL: 'AGRICULTURAL',
  CONSTRUCTION: 'CONSTRUCTION',
  PETROCHEMICAL: 'PETROCHEMICAL',
  OTHER: 'OTHER'
};

exports.VerificationStatus = exports.$Enums.VerificationStatus = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  NEEDS_REVISION: 'NEEDS_REVISION'
};

exports.DocumentType = exports.$Enums.DocumentType = {
  ESTABLISHMENT_NOTICE: 'ESTABLISHMENT_NOTICE',
  BOARD_CHANGES: 'BOARD_CHANGES',
  OPERATION_LICENSE: 'OPERATION_LICENSE',
  PRODUCTION_LICENSE: 'PRODUCTION_LICENSE',
  GUILD_LICENSE: 'GUILD_LICENSE',
  KNOWLEDGE_BASED_LICENSE: 'KNOWLEDGE_BASED_LICENSE',
  OTHER_LICENSES: 'OTHER_LICENSES',
  ISO_CERTIFICATE: 'ISO_CERTIFICATE',
  BUSINESS_CARD: 'BUSINESS_CARD',
  ID_DOCUMENT: 'ID_DOCUMENT'
};

exports.ProductOrigin = exports.$Enums.ProductOrigin = {
  DOMESTIC_FACTORY: 'DOMESTIC_FACTORY',
  KNOWLEDGE_BASED: 'KNOWLEDGE_BASED',
  IMPORTED: 'IMPORTED'
};

exports.DeliveryTerms = exports.$Enums.DeliveryTerms = {
  EXW: 'EXW',
  FCA: 'FCA',
  FOB: 'FOB'
};

exports.PaymentMethod = exports.$Enums.PaymentMethod = {
  LC: 'LC',
  SBLC: 'SBLC',
  TT: 'TT'
};

exports.TradeType = exports.$Enums.TradeType = {
  BUY: 'BUY',
  SELL: 'SELL'
};

exports.TradeRequestStatus = exports.$Enums.TradeRequestStatus = {
  PENDING: 'PENDING',
  MATCHED: 'MATCHED',
  IN_NEGOTIATION: 'IN_NEGOTIATION',
  UNDER_REVIEW: 'UNDER_REVIEW',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

exports.AdStatus = exports.$Enums.AdStatus = {
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  PAUSED: 'PAUSED',
  REJECTED: 'REJECTED',
  EXPIRED: 'EXPIRED'
};

exports.SupportTicketStatus = exports.$Enums.SupportTicketStatus = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED'
};

exports.ChatMessageRole = exports.$Enums.ChatMessageRole = {
  USER: 'USER',
  ASSISTANT: 'ASSISTANT',
  SYSTEM: 'SYSTEM'
};

exports.ConsultationCategory = exports.$Enums.ConsultationCategory = {
  COMMERCIAL: 'COMMERCIAL',
  TECHNICAL: 'TECHNICAL',
  LEGAL: 'LEGAL',
  FINANCIAL: 'FINANCIAL',
  CUSTOMS: 'CUSTOMS',
  CURRENCY: 'CURRENCY',
  COMMODITY_PURCHASE: 'COMMODITY_PURCHASE',
  FOREX_OBLIGATIONS: 'FOREX_OBLIGATIONS',
  LOGISTICS: 'LOGISTICS'
};

exports.AnalysisRequestStatus = exports.$Enums.AnalysisRequestStatus = {
  SUBMITTED: 'SUBMITTED',
  IN_REVIEW: 'IN_REVIEW',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
};

exports.NotificationType = exports.$Enums.NotificationType = {
  TRADE_REQUEST_MATCH: 'TRADE_REQUEST_MATCH',
  PRODUCT_APPROVED: 'PRODUCT_APPROVED',
  DOCUMENT_VERIFIED: 'DOCUMENT_VERIFIED',
  NEW_MESSAGE: 'NEW_MESSAGE',
  SYSTEM_ANNOUNCEMENT: 'SYSTEM_ANNOUNCEMENT'
};

exports.Prisma.ModelName = {
  User: 'User',
  AdminProfile: 'AdminProfile',
  OtpCode: 'OtpCode',
  RefreshToken: 'RefreshToken',
  UserProfile: 'UserProfile',
  Document: 'Document',
  Product: 'Product',
  ProductMedia: 'ProductMedia',
  TradeRequest: 'TradeRequest',
  TradeAttachment: 'TradeAttachment',
  HsCode: 'HsCode',
  IsicCode: 'IsicCode',
  Circular: 'Circular',
  DownloadItem: 'DownloadItem',
  Advertisement: 'Advertisement',
  SupportTicket: 'SupportTicket',
  SupportMessage: 'SupportMessage',
  AiConversation: 'AiConversation',
  AiMessage: 'AiMessage',
  AnalysisRequest: 'AnalysisRequest',
  News: 'News',
  NewsletterSubscription: 'NewsletterSubscription',
  Survey: 'Survey',
  SurveyResponse: 'SurveyResponse',
  ContactMessage: 'ContactMessage',
  Conversation: 'Conversation',
  ConversationParticipant: 'ConversationParticipant',
  Message: 'Message',
  Notification: 'Notification'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
